openapi: 3.0.3
info:
  version: '1.0.0'
  title: Morsum Cart API
  description: API that gets items info

servers:
  - url: http://localhost/api/v1

tags:
  - name: Products
    description: Operations with products


paths:
  /products:
    summary: Operations with products
    get:
      tags:
        - product
      summary: get all the products
      responses:
        200:
          description: Success
          content: 
            application/json:
        400:
          description: Incorrect input
        default:
          description: Success
        

